global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs: [{ targets: ['prometheus:9090'] }]

  - job_name: node
    static_configs: [{ targets: ['localhost:9100'] }]

  - job_name: cadvisor
    static_configs: [{ targets: ['cadvisor:8080'] }]

  - job_name: dcgm
    static_configs: [{ targets: ['dcgm-exporter:9400'] }]

  - job_name: opshub
    static_configs: [{ targets: ['opshub:9188'] }]
